"""Pruebas en el navegador: prueba buscador. Se corren con tests/e2e/run.py."""
from playwright.sync_api import sync_playwright
from comun import API, BASE, FX, salida
OUT = salida('buscador')
res=[]
def check(n,c,d=''): res.append(bool(c)); print(('OK  ' if c else 'FAIL'), n, d)
def visible(page): return page.eval_on_selector_all('.tile', "els => els.filter(a => !a.closest('li').hidden).map(a => a.querySelector('.tile-name').textContent)")
with sync_playwright() as p:
    b=p.chromium.launch(); page=b.new_page(); errs=[]
    page.on('pageerror', lambda e: errs.append(str(e)))
    page.goto(BASE); page.wait_for_timeout(600)
    check('27 fichas al inicio', len(visible(page)) == 27, len(visible(page)))
    page.fill('#buscar', 'word')
    v = visible(page); check('buscar «word»', sorted(v) == ['PDF a Word', 'Word a PDF'], v)
    page.fill('#buscar', 'contraseña')
    v = visible(page); check('buscar con tilde «contraseña»', set(v) == {'Proteger PDF', 'Desbloquear PDF'}, v)
    page.fill('#buscar', 'JUNTAR')
    v = visible(page); check('mayúsculas y sinónimo «JUNTAR»', v == ['Unir PDF'], v)
    page.fill('#buscar', 'xyzabc')
    check('sin resultados: aviso', page.is_visible('[data-empty]') and not visible(page), page.inner_text('[data-empty]') if page.is_visible('[data-empty]') else '')
    check('sin resultados: grupos ocultos', page.eval_on_selector_all('.tool-group', 'els => els.every(e => e.hidden)'))
    page.fill('#buscar', '')
    page.click('[data-filter="editar"]')
    v = visible(page); check('filtro Editar', set(v) == {'Números de página', 'Marca de agua', 'Recortar PDF'}, v)
    check('filtro marcado', page.get_attribute('[data-filter="editar"]', 'aria-pressed') == 'true' and page.get_attribute('[data-filter=""]', 'aria-pressed') == 'false')
    page.fill('#buscar', 'word')
    check('filtro + búsqueda', visible(page) == [], visible(page))
    page.fill('#buscar', 'pdf a')
    check('palabras de una letra no filtran', visible(page) == ['Recortar PDF'], visible(page))
    page.click('[data-filter=""]')
    page.fill('#buscar', 'comprimir')
    page.press('#buscar', 'Enter'); page.wait_for_load_state(); page.wait_for_timeout(300)
    check('Enter con un solo resultado abre la herramienta', page.url.endswith('/comprimir/'), page.url)
    page.goto(BASE); page.wait_for_timeout(300)
    page.keyboard.press('/')
    check('«/» lleva al buscador', page.evaluate("document.activeElement.id") == 'buscar')
    page.goto(BASE+'unir/'); page.wait_for_timeout(300)
    rel = page.eval_on_selector_all('.related .tile-name', 'els => els.map(e => e.textContent)')
    check('herramientas relacionadas', len(rel) == 4 and 'Unir PDF' not in rel, rel)
    check('sin errores', not errs, errs[:3])
    b.close()
print(f'{sum(res)}/{len(res)} pruebas bien')
raise SystemExit(0 if res and all(res) else 1)
